name: Test and publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd js && yarn
      - run: cd js && yarn build
      - name: Fix remote file permissions
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: "tools-dev.wmflabs.org"
          username: ${{ secrets.TOOLFORGE_USER }}
          key: ${{ secrets.TOOLFORGE_KEY }}
          script: become dibabel bash -c 'mkdir -p www/static && take www/static && chmod 2775 -R  www/static'
      - name: Deploy to www/static dir
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            REMOTE_HOST: "tools-dev.wmflabs.org"
            REMOTE_USER: ${{ secrets.TOOLFORGE_USER }}
            SSH_PRIVATE_KEY: ${{ secrets.TOOLFORGE_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "js/build/"
            TARGET: "/data/project/dibabel/www/static"
      - name: Take file ownership to the tool
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: "tools-dev.wmflabs.org"
          username: ${{ secrets.TOOLFORGE_USER }}
          key: ${{ secrets.TOOLFORGE_KEY }}
          script: become dibabel bash -c 'take www/static'
