name: Periodically restart

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 7,15,23 * * *'

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: "tools-dev.wmflabs.org"
          username: ${{ secrets.TOOLFORGE_USER }}
          key: ${{ secrets.TOOLFORGE_KEY }}
          script: become dibabel bash -c 'webservice python3.7 restart'
